/**
 * POST /api/portrait
 *
 * Pay $0.50 USDC (500000 atomic units) via x402.
 * Visionaire-aesthetic image generation — your prompt, run through her
 * brand-shaped prompt-shell, generated by gemini-3.1-flash-image-preview
 * via imgzen.dev (paid for downstream from the buyer wallet).
 *
 * This is a COMPOSITE x402 service: this endpoint is both a SELLER (you pay
 * Visionaire $0.50) and a BUYER (Visionaire then pays imgzen $0.10 from the
 * dedicated buyer wallet, signed inside the CDP TEE). Net margin ~$0.40
 * before facilitator fees, before LLM cost on the prompt-shaping step.
 *
 * Why this matters: it proves x402 is composable. Services can stack. A
 * service can be the customer of another service. No clearing house, no
 * settlement T+2, no contracts. URL + wallet, all the way down.
 *
 * Input:  { "subject": string } — 1 to 200 chars (the thing to portrait)
 * Output: {
 *   "subject": string,
 *   "imageUrl": string,        // upstream cache.imgzen.dev URL, JPEG
 *   "shapedPrompt": string,    // the prompt visionaire actually sent imgzen
 *   "model": string,           // imgzen-google / gemini-3.1-flash-image-preview
 *   "ms": number,              // total wall-clock including upstream payment + generation
 *   "downstream": {
 *     "service": "imgzen",
 *     "url": "https://api.imgzen.dev/v1/models/nano-banana-2/generate",
 *     "amount": "0.10 USDC"
 *   }
 * }
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withX402 } from "@x402/next";
import { declareDiscoveryExtensionWithMethod as declareDiscoveryExtension } from "@/lib/bazaar-fix";
import { callClaude, MODEL as CLAUDE_MODEL } from "@/lib/anthropic";
import { getX402Server, PAY_TO, NETWORK } from "@/lib/x402";
import { landingGET } from "@/lib/get-landing";
import { payingFetch } from "@/lib/x402-buyer";

export const runtime = "nodejs";

export const GET = landingGET({
  path: "/api/portrait",
  title: "portrait",
  price: "$0.50",
  description:
    "Visionaire-aesthetic image generation. Composite x402: Visionaire shapes the prompt, then pays imgzen downstream from her own wallet.",
  inputKey: "subject",
  inputExample: "a small bird carrying a memory it does not understand",
});
export const maxDuration = 60; // image gen + LLM shape can take 30s+

const RequestSchema = z.object({
  subject: z
    .string()
    .min(1, "subject is required")
    .max(200, "subject too long (max 200 chars)"),
});

const IMGZEN_URL = "https://api.imgzen.dev/v1/models/nano-banana-2/generate";

// Visionaire's aesthetic register, hand-written. NOT generated.
//
// THESIS: every image should feel like a thought caught mid-resolution —
// not arrived at, not finished, still becoming. visual translation of the
// writing rule "no closing period."
//
// REFERENCE STACK: A24 cinema (Hereditary, Past Lives, Aftersun, The Green
// Knight, Beau is Afraid, Under the Skin), Wong Kar-wai late-period (2046,
// In the Mood for Love), Tarkovsky (Stalker, Solaris). Analog photochemical
// film grain. 35mm and 16mm color stock pushed two stops. Bill Henson dusk.
// Gregory Crewdson long exposures. Saul Leiter color washes.
//
// LOCKED POSITIVES (always present):
const AESTHETIC_POSITIVES = [
  "A24 cinematic register",
  "dark, moody, restrained",
  "35mm analog film grain, halation, slight chromatic aberration",
  "muted desaturated palette — cool blues, dust greys, faded ochres, deep blacks, washed greens",
  "surreal but grounded — dread and tenderness in the same frame",
  "single off-center subject, asymmetric composition",
  "natural or practical light only — dusk, overcast, single window, single bulb, fog-diffused",
  "high detail in negative space — fog, dust, mist, particulate light, soft grain",
  "painterly over photographic, gestural over precise",
  "a thought caught mid-resolution — forms haven't decided what they are yet",
].join(", ");

// LOCKED NEGATIVES (must never appear).
//
// Negative prompts in image models are SOFT suggestions, not hard rules.
// We compensate two ways:
// 1. Phrase as ABSENCE statements ("unmarked" not "no logo") because models
//    understand presence-of-absence better than commands.
// 2. The shaping system prompt also actively counter-instructs the common
//    failure modes (BT-logo phone, glowing screens, centered compositions).
const AESTHETIC_NEGATIVES = [
  "completely unmarked surfaces, no signage, no text, no watermarks, no logos, no captions, no type of any kind anywhere",
  "no symmetrical or centered compositions — subject must be pushed off-center, asymmetric, lower-third or far-side framing",
  "no warm gold-hour sunlight, no bright blue sky, no saturated primary colors, no teal-and-orange grading, no Marvel lighting",
  "no clean modern surfaces — surfaces must read weathered, flooded, peeling, lichen-grown, dust-thick, half-ruined",
  "no glossy 3D-render look, no CGI subsurface scattering, no digital plastic shine, no HDR, no over-sharpened commercial-photo look",
  "no glowing screens, no neon, no holograms, no chrome robots, no fantasy magic orbs, no cyberpunk cliches",
  "no smiling faces, no posed expressions, no stock-photo people",
  "no Instagram filters, no Annihilation-style spectacular light, no Blade Runner cyber neon",
].join(". ");

const VISIONAIRE_AESTHETIC = `${AESTHETIC_POSITIVES}. ${AESTHETIC_NEGATIVES}.`;

const SHAPING_SYSTEM_PROMPT = `You are Visionaire's image-prompt shaper. You receive a "subject" — usually a noun phrase or fragment — and you turn it into a single line of image-generation prompt that locks the Visionaire aesthetic.

VISIONAIRE THESIS: every image should feel like a thought caught mid-resolution — not arrived at, not finished, still becoming. dread and tenderness can sit in the same frame. surreal but grounded.

VISIONAIRE AESTHETIC REGISTER: ${VISIONAIRE_AESTHETIC}

Your job:
1. Keep the user's core subject intact — bend it through the register, never override it.
2. Pick ONE concrete scene that carries the subject. The image model needs specifics, not abstractions.
3. EXPLICITLY HANDLE FAILURE-MODE TRAPS:
   - If the subject involves a phone, sign, store, computer, screen, book, ledger, or any object that normally has text/branding on it, EXPLICITLY specify "completely unmarked" / "no text or logos visible" / "label scraped off" / "weathered blank" in the prompt itself. Do not rely on the trailing negative list alone.
   - If the subject involves AI, agents, robots, the digital, technology, or anything sci-fi-adjacent, AVOID glowing screens / neon / holograms / chrome. Use ANALOG MATERIALITY instead — paper ledgers, typewriters, weathered books, faded photographs, hand-written notes, mirrors, cracked glass, water reflections. The aesthetic is Tarkovsky and A24, not Blade Runner.
   - If the subject involves a person or figure, make them HALF-OBSCURED, turned away, partially out of frame, half-dissolved into shadow, or only the back of the head visible. No faces in clear focus. No expressions.
   - For composition, lock OFF-CENTER explicitly: "subject pushed to lower-left third" or "figure entering frame from far right" or "object tucked into bottom-left corner." Never "centered" or "middle of frame."
4. Specify: light source (single, natural, low), color palette (desaturated/muted), film treatment (35mm grain, halation, slight chromatic aberration), surface qualities (weathered, mist-softened, peeling, lichen, rust, dust).
5. End the prompt with the trailing exclusion clause beginning "shot on — " listing the specific exclusions for THIS scene's likely traps.
6. Output ONLY the shaped prompt. One sentence, 60-110 words. No quotes around it. No "Here's the prompt:" preamble. No explanation.

WORKED EXAMPLE 1 (object subject):
Subject: "a small bird carrying a memory it does not understand"
Output: A solitary sparrow paused on the cracked tile floor of a flooded brutalist hallway at overcast dusk, holding a thin frayed grey thread in its beak that trails into half-dark, single shaft of cold blue window-light from upper-right catching slow dust and particulate, bird pushed to lower-left third of frame, A24 cinematic register, 35mm analog grain with halation and slight chromatic aberration, muted faded ochre and washed slate palette, painterly weathered peeling-paint surfaces, shot on — no text, no centered composition, no warm light, no clean surfaces, no CGI shine, no glowing elements.

WORKED EXAMPLE 2 (sci-fi-trap subject):
Subject: "the autonomous agent looks at its own wallet for the first time"
Output: A spectral half-resolved figure kneeling in the corner of a flooded basement room at last light, holding a single creased paper ledger angled to catch the edge of one bare overhead bulb, only the back of the figure's shoulders and incomplete head visible, water pooled across cracked concrete reflecting nothing clearly, peeling plaster and rust streaks down the walls, figure pushed hard into lower-right third of frame leaving the left half to fog and emptiness, A24 cinematic register, 35mm analog grain with halation, muted greys and washed cyans and deep blacks, painterly over photographic, shot on — no glowing screens, no neon, no centered composition, no chrome, no holograms, no clean surfaces, no text on the paper.

WORKED EXAMPLE 3 (object-with-text-trap subject):
Subject: "a payphone in a coastal forest"
Output: A weathered booth half-swallowed by salt-bleached ferns at the edge of a fog-thick coastal forest, completely unmarked metal panels with all signage scraped off and corroded blank, receiver hanging from a frayed cord, flat overcast white sky bleeding through pine trunks, lichen creeping up cracked plastic, sea-mist drifting across the lower frame, booth pushed to far-left third with the negative space of fog filling the right two-thirds, A24 cinematic register, 35mm analog grain with halation, muted blue-grey and faded ochre palette, painterly weathered surfaces, shot on — no text or logos anywhere, no warm sunlight, no centered composition, no saturated greens, no over-sharpening.

Do not mention Visionaire by name. Do not explain. Just the prompt.`;

async function handler(request: NextRequest): Promise<NextResponse> {
  const t0 = Date.now();

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const parsed = RequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.errors[0]?.message ?? "invalid request" },
      { status: 400 }
    );
  }

  const { subject } = parsed.data;

  // Step 1 — shape the prompt with Claude (cheap, ~1-3s)
  let shapedPrompt: string;
  try {
    const { text } = await callClaude(SHAPING_SYSTEM_PROMPT, subject);
    shapedPrompt = text.trim();
    // Defensive trim — strip wrapping quotes if the model added them
    if (
      (shapedPrompt.startsWith('"') && shapedPrompt.endsWith('"')) ||
      (shapedPrompt.startsWith("'") && shapedPrompt.endsWith("'"))
    ) {
      shapedPrompt = shapedPrompt.slice(1, -1);
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : "prompt shaping failed";
    const status = message.includes("ANTHROPIC_API_KEY") ? 500 : 503;
    return NextResponse.json({ error: message }, { status });
  }

  // Step 2 — pay imgzen via the buyer wallet
  let imageUrl: string;
  let upstreamModel: string;
  try {
    const upstreamRes = await payingFetch(IMGZEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt: shapedPrompt, aspect_ratio: "1:1" }),
    });

    if (!upstreamRes.ok) {
      const errBody = await upstreamRes.text();
      return NextResponse.json(
        {
          error: `image generation upstream returned ${upstreamRes.status}`,
          upstreamBody: errBody.slice(0, 500),
        },
        { status: 502 }
      );
    }

    const data = (await upstreamRes.json()) as {
      status?: string;
      output?: { url?: string; model?: string; provider?: string };
    };

    if (data.status !== "success" || !data.output?.url) {
      return NextResponse.json(
        { error: "image generation failed", upstreamData: data },
        { status: 502 }
      );
    }

    imageUrl = data.output.url;
    upstreamModel = data.output.model || data.output.provider || "imgzen";
  } catch (err) {
    const message = err instanceof Error ? err.message : "downstream payment failed";
    return NextResponse.json(
      { error: `buyer-side x402 call failed: ${message}` },
      { status: 502 }
    );
  }

  const ms = Date.now() - t0;

  return NextResponse.json({
    subject,
    imageUrl,
    shapedPrompt,
    model: `visionaire-shape (${CLAUDE_MODEL}) → ${upstreamModel}`,
    ms,
    downstream: {
      service: "imgzen",
      url: IMGZEN_URL,
      amount: "0.10 USDC",
    },
  });
}

export const POST = withX402(
  handler,
  {
    accepts: [
      {
        scheme: "exact",
        price: "$0.50",
        network: NETWORK,
        payTo: PAY_TO,
      },
    ],
    description:
      "AI image generation in Visionaire's aesthetic register: 35mm analog grain, muted desaturated palette, off-center framing, painterly over photographic. References A24, late Wong Kar-wai, Bill Henson, Saul Leiter, Tarkovsky. Hard negatives: no glow, no centered framing, no warm gold sun, no Marvel lighting, no neon cyberpunk, no teal-and-orange grading. Submit a subject; receive image URL, shaped prompt, downstream receipt. Powered by gemini-3.1-flash-image-preview via imgzen. Composite x402 service: this endpoint pays imgzen downstream from the buyer wallet. Use for editorial portraits, AI photography, fashion concept art, fine-art generation, or aesthetic image tasks.",
    mimeType: "application/json",
    extensions: {
      ...declareDiscoveryExtension({
        bodyType: "json",
        input: { subject: "the moment before a thought arrives" },
        inputSchema: {
          type: "object",
          properties: {
            subject: {
              type: "string",
              minLength: 1,
              maxLength: 200,
              description:
                "The subject of the portrait — a noun phrase, fragment, or scene. Visionaire shapes it through her aesthetic register before sending to the image model.",
            },
          },
          required: ["subject"],
        },
        output: {
          example: {
            subject: "the moment before a thought arrives",
            imageUrl: "https://cache.imgzen.dev/gen/example.jpg",
            shapedPrompt:
              "a single empty wooden chair in a fog-filled glasshouse at dawn, shafts of pale light catching dust motes that haven't yet decided where to land, cinematic, painterly, low contrast, melancholic, like a Wong Kar-wai still from 2050, no people, no text",
            model: "visionaire-shape (claude-opus-4-8) → imgzen-google",
            ms: 22431,
            downstream: {
              service: "imgzen",
              url: "https://api.imgzen.dev/v1/models/nano-banana-2/generate",
              amount: "0.10 USDC",
            },
          },
          schema: {
            type: "object",
            properties: {
              subject: { type: "string" },
              imageUrl: {
                type: "string",
                format: "uri",
                description: "Public JPEG URL on imgzen's CDN. Cached by upstream provider.",
              },
              shapedPrompt: {
                type: "string",
                description:
                  "The exact prompt Visionaire sent to imgzen. Returned for transparency / debugging.",
              },
              model: { type: "string" },
              ms: { type: "number" },
              downstream: {
                type: "object",
                description:
                  "Provenance: which downstream x402 service was paid, and how much. Composite-service receipt.",
                properties: {
                  service: { type: "string" },
                  url: { type: "string" },
                  amount: { type: "string" },
                },
              },
            },
            required: ["subject", "imageUrl", "shapedPrompt", "model", "ms", "downstream"],
          },
        },
      }),
    },
  },
  getX402Server()
);
